config/routes.rb
RamusKlient::Application.routes.draw do
  
  resources :histories

  resources :kontaktni_osobas

  resources :zajem_o_informaces

  resources :leks

  resources :klient_leks

  resources :klients

  resources :osobas

  root "klients#index"

  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"
  
  namespace :admin do
    root "base#index"
    resources :users
  end
    
end

app/models/history.rb
class History < ActiveRecord::Base
    belongs_to :user

end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render action: 'show', status: :created, location: @history }
      else
        format.html { render action: 'new' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:object_name, :object_id, :attribute_name, :before_value, :after_value, :user_id)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :object_name %><br>
    <%= f.text_field :object_name %>
  </div>
  <div class="field">
    <%= f.label :object_id %><br>
    <%= f.number_field :object_id %>
  </div>
  <div class="field">
    <%= f.label :attribute_name %><br>
    <%= f.text_field :attribute_name %>
  </div>
  <div class="field">
    <%= f.label :before_value %><br>
    <%= f.text_field :before_value %>
  </div>
  <div class="field">
    <%= f.label :after_value %><br>
    <%= f.text_field :after_value %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<h1>Listing histories</h1>

<table id='histtable' class="table table-striped">
  <thead>
    <tr>
      <th>Čas změny</th>
      <th>Změněn</th>
      <th>Změněný atribut</th>
      <th>Hodnota před</th>
      <th>Hodnota po</th>
      <th>Změnil</th>
      <th>smaž</th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
    
    <tr>

      <% if history.updated_at? %>
      <td><%= history.updated_at.strftime('%Y-%m-%d, %H:%M:%S') %></td>
      <% else %>
      <td><%= history.created_at %></td>
      <% end %>

      <% if history.object_id? %>
      <% case history.object_name %>
      <% when 'Osoba' %>
      <td><%= Osoba.find(history.object_id).jmeno + ' ' + Osoba.find(history.object_id).prijmeni %></td>
      <% when 'Klient' %>
      <td><%= Osoba.find(Klient.find(history.object_id).osoba_id).jmeno + ' ' + Osoba.find(Klient.find(history.object_id).osoba_id).prijmeni %></td>
      <% when 'KontaktniOsoba' %>
      <td><%= Osoba.find(Klient.find(KlientsKontaktniOsoba.find(KontaktniOsoba.find(history.object_id).id).klient_id).osoba_id).jmeno + ' ' + Osoba.find(Klient.find(KlientsKontaktniOsoba.find(KontaktniOsoba.find(history.object_id).id).klient_id).osoba_id).prijmeni %></td>
      <% when 'Lek' %>
      <td><%= Osoba.find(Klient.find(Lek.find(history.object_id).klient_id).osoba_id).jmeno + ' ' + Osoba.find(Klient.find(Lek.find(history.object_id).klient_id).osoba_id).prijmeni %></td>
      <% when 'ZajemOInformace' %>
      <td><%= Osoba.find(Klient.find(ZajemOInformace.find(history.object_id).klient_id).osoba_id).jmeno + ' ' + Osoba.find(Klient.find(ZajemOInformace.find(history.object_id).klient_id).osoba_id).prijmeni %></td>
      <% else %>
      <td><%= history.object_name + ' ' + history.object_id.to_s %>
        <% end %>
        <% else %>
        <td></td>
        <% end %>

        <td><%= history.attribute_name %></td>
        <td><%= history.before_value %></td>
        <td><%= history.after_value %></td>
        <td><%= User.find(history.user_id).username %></td>
        <td class='center'><%= link_to "\u2715", history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Object name:</strong>
  <%= @history.object_name %>
</p>

<p>
  <strong>Object:</strong>
  <%= @history.object_id %>
</p>

<p>
  <strong>Attribute name:</strong>
  <%= @history.attribute_name %>
</p>

<p>
  <strong>Before value:</strong>
  <%= @history.before_value %>
</p>

<p>
  <strong>After value:</strong>
  <%= @history.after_value %>
</p>

<p>
  <strong>User:</strong>
  <%= @history.user %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>