config/routes.rb
RamusKlient::Application.routes.draw do
  
  resources :histories

  resources :kontaktni_osobas

  resources :zajem_o_informaces

  resources :leks

  resources :klient_leks

  resources :klients

  resources :osobas

  root "klients#index"

  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"
  
  namespace :admin do
    root "base#index"
    resources :users
  end
    
end

app/models/klient.rb
class Klient < ActiveRecord::Base
  include ActiveModel::Dirty

  after_create :write_history
  before_update :write_history
  
  belongs_to :osoba
  has_many :leks
  has_many :klients_kontaktni_osobas
  # has_many :klient_leks
  has_many :kontaktni_osobas, through: :klients_kontaktni_osobas, class_name: 'KontaktniOsoba'
  has_one :zajem_o_informace, :dependent => :destroy

  accepts_nested_attributes_for :leks, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :kontaktni_osobas, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :osoba, reject_if: :all_blank, allow_destroy: true
  # accepts_nested_attributes_for :klient_leks, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :zajem_o_informace, reject_if: :all_blank, allow_destroy: true


  # validations

  # validates :elektronicky_souhlas_s_uchovanim_udaju, acceptance: true

  private
  def write_history
    self.changes.each do |attribute_name, values|
      before_value = values[0].to_s.truncate(700) if !values[0].nil?
      after_value = values[1].to_s.truncate(700) if !values[1].nil?
      user_id = User.current.id
      History.create!({:object_name => self.class.name,
       :object_id => self.id,
       :attribute_name => attribute_name,
       :before_value => before_value.to_s,
       :after_value => after_value.to_s,
       :user_id => user_id})
    end
  end

end

app/controllers/klients_controller.rb
class KlientsController < ApplicationController
  before_action :require_signin!
  before_action :set_klient, only: [:show, :edit, :update, :destroy]

  # GET /klients
  # GET /klients.json
  def index
    if current_user.admin? == false
      @klient = Klient.find_by osoba_id: current_user.osoba.id
      redirect_to action: 'edit', id:current_user.osoba.id
    elsif current_user.admin?
      @klients = Klient.all
    else
      redirect_to(signin_path)
    end
  end

  # GET /klients/1
  # GET /klients/1.json
  def show
    if current_user.admin?
      @kontaktni_osobas = KontaktniOsoba.all
    else
      redirect_to(root_path)
    end

    if @klient.vozickar
      @vozickar = "\u2713"
    else
      @vozickar = "\u2A2F"
    end

    if @klient.epilepsie
      @epilepsie = "\u2713"
    else
      @epilepsie = "\u2A2F"
    end

    if @klient.inkontinence
      @inkontinence = "\u2713"
    else
      @inkontinence = "\u2A2F"
    end


    # checking plnoletost
    rc = @klient.rodne_cislo[0,6]
    rc = rc[0,2].to_s + ',' + rc[2,2].to_s + ',' + rc[4,2].to_s

    # datum_narozeni = DateTime.strptime('{rc}','{%y%m%d}')

    if @klient.rodne_cislo[1,6].to_i < (Time.now.strftime('%Y%m%d').to_i)
      @plnoletost = "\u2713"
    else
      @plnoletost = "\u2A2F"
    end

    @plnoletost = 'TBI'

    if @klient.elektronicky_souhlas_s_uchovanim_udaju
      @elektronicky_souhlas_s_uchovanim_udaju = "\u2713"
    else
      @elektronicky_souhlas_s_uchovanim_udaju = "\u2A2F"
    end

    if @klient.souhlas_s_uverejnenim_foto_video
      @souhlas_s_uverejnenim_foto_video = "\u2713"
    else
      @souhlas_s_uverejnenim_foto_video = "\u2A2F"
    end

    if @klient.platny_zaznam
      @platny_zaznam = "\u2713"
    else
      @platny_zaznam = "\u2A2F"
    end

    @adresa = @klient.osoba.ulice.to_s + ' ' + @klient.osoba.cislo_popisne.to_s + 
    '/' + @klient.osoba.cislo_orientacni.to_s + ',' + 
    @klient.osoba.mesto.to_s + ' ' + @klient.osoba.psc.to_s
  end

  # GET /klients/new
  def new
    @klient = Klient.new
    @klient.build_osoba()
    # @kontaktni_osobas = KontaktniOsoba.all
  end

  # GET /klients/1/edit
  def edit
    # @kontaktni_osobas = KontaktniOsoba.all
    # if current_user.admin?
    #   redirect_to action: 'index'
    # end
  end

  # POST /klients
  # POST /klients.json
  def create
    @klient = Klient.new(klient_params)

    respond_to do |format|
      if @klient.save
        format.html { redirect_to @klient, notice: 'Klient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @klient }
      else
        format.html { render action: 'new' }
        format.json { render json: @klient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /klients/1
  # PATCH/PUT /klients/1.json
  def update
    respond_to do |format|
      if @klient.update(klient_params)
        format.html { redirect_to @klient, notice: 'Klient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @klient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /klients/1
  # DELETE /klients/1.json
  def destroy
    @klient.destroy
    respond_to do |format|
      format.html { redirect_to klients_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klient
      if current_user.admin?
        @klient = Klient.find(params[:id])    
      else
        @klient = Klient.find_by osoba_id: current_user.osoba.id
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klient_params
      params.require(:klient).permit(:osoba_id, :rodne_cislo, :pojistovna, :vozickar, :epilepsie,
       :podoba_epileptickeho_zachvatu, :prukaz, :alergie, :inkontinence,
       :popis_projevu_diagnozy_a_instrukce_k_zachazeni_s_klientem, :denni_rezim,
       :plnoletost, :postrehy_ramus, :sklony_k_oddelovani_se_od_skupiny,
       :elektronicky_souhlas_s_uchovanim_udaju, :souhlas_s_uverejnenim_foto_video,
       :diagnoza, :platny_zaznam,
       osoba_attributes:[:id, :kontaktni_osoba_id, :jmeno, :prijmeni, :email, :telefon, :ulice, :cislo_popisne,
        :cislo_orientacni, :psc, :mesto],
        kontaktni_osobas_attributes:[:id, :osoba_id, :klient_id, :vztah_ke_klientovi, :jmeno, :prijmeni, :email,
         :telefon, :ulice, :cislo_popisne, :cislo_orientacni, :psc, :mesto, :_destroy],
         :kontaktni_osobas_ids => [],
         klient_leks_attributes:[:id, :klient_id, :lek_id, :davkovani],
         leks_attributes:[:id, :klient_id, :nazev, :pribalovy_letak, :davkovani, :_destroy],
         zajem_o_informace_attributes:[:id, :klient_id, :jemne_vikendovky, :drsne_vikendovky, :humr, :rambar, :dilna,
           :legendarni_tabory, :drsne_tabory, :_destroy])
end
end

app/helpers/klients_helper.rb
module KlientsHelper
end

app/views/klients/_form.html.erb
<%= form_for @klient, :html => {:class => "form-horizontal"} do |f| %>
<% if @klient.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@klient.errors.count, "error") %> prohibited this klient from being saved:</h2>

  <ul>
    <% @klient.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row form-border">
  <div class="col-md-3">
    <div class="field">
      <%= f.label :rodne_cislo, 'rodné číslo' %>
      <br>
      <%= f.text_field :rodne_cislo, :class=>'col-md-12' %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="field">
      <%= f.label :pojistovna, 'číslo pojišťovny' %>
      <br>
      <%= f.text_field :pojistovna, :class=>'col-md-12' %>
    </div>
  </div>

  <%= f.fields_for :osoba do |osobaf| %>
  <div class="col-md-3">
    <div class="field">
      <%= osobaf.label :email, 'email' %>
      <br>
      <%= osobaf.text_field :email, :class=>'col-md-12' %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="field">
      <%= osobaf.label :telefon, 'telefon' %>
      <br>
      <%= osobaf.text_field :telefon, :class=>'col-md-12' %>
    </div>
  </div>
</div>

<br><h3>::adresa</h3>

<div class="row form-border">
  <div class="col-md-3">
    <div class="field">
      <%= osobaf.label :ulice, 'ulice' %>
      <br>
      <%= osobaf.text_field :ulice, :class=>'col-md-12' %>
    </div>
  </div>
  <div class="col-md-2">
    <div class="field">
      <%= osobaf.label :cislo_popisne, 'číslo popisné' %>
      <br>
      <%= osobaf.text_field :cislo_popisne %>
    </div>
  </div>
  <div class="col-md-2">
    <div class="field">
      <%= osobaf.label :cislo_orientacni, 'číslo orientační' %>
      <br>
      <%= osobaf.text_field :cislo_orientacni %>
    </div>
  </div>
  <div class="col-md-2">
    <div class="field">
      <%= osobaf.label :psc, 'PSČ' %>
      <br>
      <%= osobaf.text_field :psc %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="field">
      <%= osobaf.label :mesto, 'město' %>
      <br>
      <%= osobaf.text_field :mesto,:class=>'col-md-12' %>
    </div>
  </div>
</div>


<% end %>

<br><h3>::kontaktní osoby</h3>
<div class="row form-border">
  <%= f.fields_for :kontaktni_osobas do |ko| %>

  <%= render 'kontaktni_osoba_fields', :f => ko %>

  <% end %>

  <div class="links">
    <br>
    <%= link_to_add_association 'přidat další kontaktní osobu', f, :kontaktni_osobas, :class => "btn btn-primary add-btn" %>
  </div>
</div>

<br><h3>::podrobnosti</h3>
<div class="row form-border">

  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <div class="col-md-2 right-align">
          <%= f.label :diagnoza, '- diagnóza' %>
        </div>
        <div class="col-md-10">
          <%= f.text_field :diagnoza, :class=>'col-md-6' %>
        </div>
      </div>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <div class="col-md-2 right-align">
          <%= f.label :popis_projevu_diagnozy_a_instrukce_k_zachazeni_s_klientem, '- popis projevů diagnózy a instrukce k zacházení s klientem' %>
        </div>
        <div class="col-md-10">
          <%= f.text_area :popis_projevu_diagnozy_a_instrukce_k_zachazeni_s_klientem, :rows => 10 %>
        </div>
      </div>
    </div>
  </div>
  <br>

  <% if current_user.admin? %>
  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <div class="col-md-2 right-align">
          <%= f.label :postrehy_ramus, '- postřehy ramusáků' %>
        </div>
        <div class="col-md-10">
          <%= f.text_area :postrehy_ramus %>
        </div>
      </div>
    </div>
  </div>
  <br>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <div class="col-md-2 right-align">
          <%= f.label :denni_rezim, '- denní režim' %>
        </div>
        <div class="col-md-10">
          <%= f.text_area :denni_rezim %>
        </div>
      </div>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <div class="col-md-2 right-align">
          <%= f.label :podoba_epileptickeho_zachvatu, '- podoba epileptického záchvatu' %>
        </div>
        <div class="col-md-10">
          <%= f.text_area :podoba_epileptickeho_zachvatu, :rows => 5 %>
        </div>
      </div>
    </div>
  </div>
  <br>
  
  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <div class="col-md-2 right-align">
          <%= f.label :alergie, '- alergie' %>
        </div>
        <div class="col-md-10"> 
          <%= f.text_area :alergie %>
        </div>
      </div>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-2 col-md-offset-3">
      <div class="field">
        <%= f.label :vozickar, 'vozíčkář?' %>
        <br>
        <%= f.check_box :vozickar %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= f.label :epilepsie, 'epileptik?' %>
        <br>
        <%= f.check_box :epilepsie%>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= f.label :inkontinence, 'inkontinentní?' %>
        <br>
        <%= f.check_box :inkontinence %>
      </div>
    </div>

    <div class="col-md-2">
      <div class="field">
        <%= f.label :prukaz, 'typ průkazu' %>
        <br>
        <%= f.select :prukaz, options_for_select(['žádný','ZTP','ZTP/P'],@klient.prukaz) %>
      </div>
    </div>
  </div>
</div>


<br><h3>::léky</h3>
<div class="row form-border">
  <%= f.fields_for :leks do |l| %>
  <%= render 'lek_fields', :f => l %>
  <% end %>
  <div class="links">
    <br>
    <%= link_to_add_association 'zadat další lék', f, :leks, :class => "btn btn-primary add-btn" %>
  </div>
</div>


<br><h3>::zájem o infomaily</h3>
<div class="row form-border">
  <%= f.fields_for :zajem_o_informace do |z| %>
  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= z.check_box :jemne_vikendovky %>
        <%= z.label :jemne_vikendovky, 'víkendovky jemné' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= z.check_box :drsne_vikendovky %>
        <%= z.label :drsne_vikendovky, 'víkendovky drsné' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= z.check_box :legendarni_tabory %>
        <%= z.label :legendarni_tabory, 'tábory legendární' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= z.check_box :drsne_tabory %>
        <%= z.label :drsne_tabory, 'tábory drsné' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= z.check_box :rambar %>
        <%= z.label :rambar, 'rambar' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= z.check_box :dilna %>
        <%= z.label :dilna, 'dílna' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= z.check_box :humr %>
        <%= z.label :humr, 'humr' %>
      </div>
    </div>
  </div>
</div>
<% end %>

<br><br><br><br>

<h3>::souhlas s uchováním údajů / použitím fotografií</h3>

<div class="row">
  <div class="col-md-12">
    <div class="field">
      <div class="col-md-1 right-align">
        <%= f.check_box :elektronicky_souhlas_s_uchovanim_udaju %>
      </div>
      <div class="col-md-11">
        <%= f.label :elektronicky_souhlas_s_uchovanim_udaju, 'Souhlasím s uchováním osobních údajů v databázi občanského sdružení Ramus, která slouží pouze pro potřeby sdružení a nebude bez výslovného souhlasu subjektu nebo jeho zákonného zástupce poskytnuta třetím osobám. Údaje budou v databázi uchovány, dokud subjekt údajů nepožádá o jejich odstranění nebo do zániku občanského sdružení Ramus. Občanské sdružení Ramus tyto údaje uchovává za účelem dodržení povinností a práv vznikajících při činnosti o.s. Ramus podle jeho platných stanov. O.s. Ramus na požádání subjektu nebo jeho zákonného zástupce vydá informace o zpracování jeho údajů a dodá vysvětlení při nejasnostech, případně sjedná nápravu podle §21 zákona 101/2000 Sb..' %>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="field">
      <div class="col-md-1 right-align">
        <%= f.check_box :souhlas_s_uverejnenim_foto_video %>
      </div>
      <div class="col-md-11">
        <%= f.label :souhlas_s_uverejnenim_foto_video, 'Souhlasím s uveřejněním fotografií a audiovizuálních záznamů výše jmenovaného občanským sdružením Ramus na internetu, v tištěné podobě, v médiích a na veřejných akcích za účelem propagace a naplnění cílů občanského sdružení Ramus.' %>
      </div>
    </div>
  </div>
</div>

<br><br>

<div class="col-md-offset-5">
  <div class="actions">
    <%= f.submit 'ULOŽIT', :class => 'btn btn-lg btn-success col-md-4' %>
  </div>
</div>
<% end %>

app/views/klients/_kontaktni_osoba_fields.erb
<div class="nested-fields nested-fields-border">

  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <div class="col-md-5">
          <h4 class="right-align"><%= f.label :vztah_ke_klientovi, 'Vztah ke klientovi', :class => 'vertical-align-middle' %>
          </h4>
        </div>
        <div class="col-md-3">
          <%= f.text_field :vztah_ke_klientovi, :style => "font-size:large; font-weight:bold" %>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label :jmeno, 'jméno' %>
        <br>
        <%= f.text_field :jmeno, :class=>'col-md-12' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :prijmeni, 'příjmení' %>
        <br>
        <%= f.text_field :prijmeni, :class=>'col-md-12' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :email, 'email' %>
        <br>
        <%= f.text_field :email, :class=>'col-md-12' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :telefon, 'telefon' %>
        <br>
        <%= f.text_field :telefon, :class=>'col-md-12' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label :ulice, 'ulice' %>
        <br>
        <%= f.text_field :ulice, :class=>'col-md-12' %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= f.label :cislo_popisne, 'číslo popisné' %>
        <br>
        <%= f.text_field :cislo_popisne, :class=>'col-md-12' %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= f.label :cislo_orientacni, 'číslo orientační' %><br>
        <%= f.text_field :cislo_orientacni, :class=>'col-md-12' %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= f.label :psc, 'PSČ' %><br>
        <%= f.text_field :psc, :class=>'col-md-12' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :mesto, 'město' %><br>
        <%= f.text_field :mesto, :class=>'col-md-12' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 col-md-offset-0"><%= link_to_remove_association "smazat tuto kontaktní osobu", f,
    confirm: 'Opravdu chcete smazat záznam této kontaktní osoby?', :class => 'btn btn-danger delete-btn' %>
   </div>
 </div>
</div>

app/views/klients/_lek_fields.erb
<div class="nested-fields nested-fields-border">

  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label :nazev, 'jméno léku' %>
        <br>
        <%= f.text_field :nazev, :class => 'col-md-12' %>
      </div>
    </div>
    <div class="col-md-9">
      <div class="field">
        <%= f.label :davkovani, 'dávkování (schématicky nebo slovně)' %>
        <br>
        <%= f.text_field :davkovani, :class => 'col-md-12' %>
      </div>
    </div>
  </div>

  <div class="md-col-1"><%= link_to_remove_association "smazat tento lék", f,
   confirm: 'Opravdu chcete smazat záznam tohoto léku?', :class => 'btn btn-danger delete-btn'  %>
 </div>
</div>

app/views/klients/edit.html.erb
<h1><%= @klient.osoba.jmeno + " " + @klient.osoba.prijmeni %></h1>

<%= render 'form' %>

app/views/klients/index.html.erb
<h1>administrace evidenčních listů</h1>

<table id='datatable' class='row-border stripe'>
	<thead>  
		<tr>
			<th>Jméno</th>
			<th>Příjmení</th>
			<th>Aktualizováno</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @klients.each do |klient| %>
		<tr>
			<td><%= klient.osoba.jmeno %></td>
			<td><%= klient.osoba.prijmeni %></td>
			<td><%= klient.updated_at.strftime('%d.%m.%Y') %></td>
			<td><%= link_to "Výpis", klient_path(klient) %></td>
			<td><%= link_to "Upravit", edit_klient_path(klient) %></td>
			<td><%= link_to "Smazat", klient, method: :delete, data: { confirm: "Chceš to fakt smazat?" } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "Nový klient", new_admin_user_path, :class => 'btn btn-primary' %>
<%= link_to 'Historie změn', histories_path, :class => 'btn btn-default' %>

app/views/klients/new.html.erb
<h1>New klient</h1>
<%= @klient.osoba.jmeno %>
sdf

<%= render 'form' %>

<%= link_to 'Back', klients_path %>

app/views/klients/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>
      <%= @klient.osoba.jmeno+' '+@klient.osoba.prijmeni %>
    </h1>
  </div>
  <div class="col-md-4">
    <h5 class='right-align'>
      <%= @klient.updated_at.strftime('naposledy aktualizováno %d.%m.%Y') %>
    </h5>
  </div>
</div>

<div class="row border-around">
  <div class="row">
    <div class="col-md-6">
      <strong>Adresa:</strong>
      <%= @adresa %>
    </div>
    <div class="col-md-3">  
      <strong>Telefon:</strong>
      <%= @klient.osoba.telefon %>
    </div>
    <div class="col-md-3">
      <strong>Email:</strong>
      <%= @klient.osoba.email %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-3">
      <strong>Rodné číslo:</strong>
      <%= @klient.rodne_cislo %>
    </div>
    <div class="col-md-3">  
      <strong>Číslo pojišťovny:</strong>
      <%= @klient.pojistovna %>
    </div>
    <div class="col-md-3">
      <strong>Druh průkazu ZTP:</strong>
      <%= @klient.prukaz %>
    </div>
    <div class="col-md-3">
      <strong>Plnoletost:</strong>
      <%= @plnoletost %>
    </div>
  </div>
</div>

<br>

<div class="row border-around">
  <div class="col-md-12">
    <p>
      <strong>Kontaktní osoby:</strong><br>
      <div class="row">
        <div class="col-md-11 col-md-offset-1">
          <% @klient.kontaktni_osobas.each do |ko| %>
          <u><%= ko.vztah_ke_klientovi %></u>:
          <%= ko.jmeno %>
          <%= ko.prijmeni %>,
          <%= ko.email %>,
          <%= ko.telefon %>
          <br>
          <% end %>
        </div>
      </div>
    </p> 
  </div>
</div>

<br>

<div class="row border-around">
  <div class="row">
    <div class='col-md-5'>
      <strong>Diagnóza:</strong>
      <%= @klient.diagnoza %>
    </div>
    <div class="col-md-2">
      <strong>Vozíčkář:</strong>
      <%= @vozickar %>
    </div>
    <div class="col-md-2">
      <strong>Epilepsie:</strong>
      <%= @epilepsie %>
    </div>
    <div class="col-md-3">
      <strong>Inkontinence:</strong>
      <%= @inkontinence %>
    </div>
  </div>

  <br> 

  <div class="row">
    <div class="col-md-12">
      <strong>Alergie:</strong>
      <%= @klient.alergie %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-12">
      <strong>Popis projevů diagnózy a instrukce k zacházení s klientem:</strong><br>
      <%= @klient.popis_projevu_diagnozy_a_instrukce_k_zachazeni_s_klientem %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-12">
      <% if @klient.epilepsie %>
      <strong>Podoba epileptického záchvatu:</strong><br>
      <%= @klient.podoba_epileptickeho_zachvatu %>
      <% end %>
    </div>
  </div>

<br>

  <div class="row">
    <div class="col-md-12">
      <strong>Podrobnosti k dennímu režimu:</strong><br>
      <%= @klient.denni_rezim %>
    </div>
  </div>

<br>

  <div class="row">
    <div class="col-md-12">
      <strong>Poznámky ramusáků:</strong><br>
      <%= @klient.postrehy_ramus %>
    </div>
  </div>
</div>

<br>

<div class="row border-around">
  <div class="col-md-12">
    <p>
      <strong>Léky:</strong><br>
      <div class="row">
        <div class="col-md-11 col-md-offset-1">
          <% @klient.leks.each do |ko| %>
          <u><%= ko.nazev %></u>:
          <%= ko.davkovani %>
          <br>
          <% end %>
        </div>
      </div>
    </p> 
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <strong>Souhlas s uchováním osobních údajů:</strong>
    <%= @elektronicky_souhlas_s_uchovanim_udaju %>
  </div>
  <div class="col-md-5">
    <strong>Souhlas s uveřejňováním audioviz. materiálů:</strong>
    <%= @souhlas_s_uverejnenim_foto_video %>
  </div>
  <div class="col-md-3">
    <strong>Platný záznam:</strong>
    <%= @platny_zaznam %>
  </div>
</div>