config/routes.rb
RamusKlient::Application.routes.draw do
  
  resources :histories

  resources :kontaktni_osobas

  resources :zajem_o_informaces

  resources :leks

  resources :klient_leks

  resources :klients

  resources :osobas

  root "klients#index"

  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"
  
  namespace :admin do
    root "base#index"
    resources :users
  end
    
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    
    <div class="row footer-first-row">
      
      <div class="col-xs-12 text-center">
        <p><small>
          &copy; Ramus IT sekce
          <br/>
          <%= link_to "Ramus.je", "http://www.ramus.je" %>
        </small></p>
      </div>
      
    </div>
    
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Ramus.je evidenční', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !current_user %>
<li><%= link_to "Přihlásit se", signin_path %></li>
<% else %>
<li><%= link_to "Odhlásit se", signout_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Ramus.je evidenční" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      
    <div class="container">
       
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>     
      </div>  
      
    </div>
  </div>
    
  <%= render 'layouts/footer' %>    

</body>
</html>